### PR TITLE
Update publications.md

### PR DESCRIPTION
**Pull request by tremblap**
added quotation marks to the website titles

### CODE REVIEW

**Comment by weefuzzy** [comment]
Cheers for that. I'm not completely sure I prefer it with quotation marks. The underline from the link seems to make it clear enough what's the title. But if you prefer it, I'll go ahead and merge.

**Comment by tremblap** [comment]
I personally hate it, but these few items did not have them - feel free to change them all to underline only but that leaves us with a problem for the material that has no active link...

**Comment by weefuzzy** [comment]
> I personally hate it, but these few items did not have them - feel free to change them all to underline only but that leaves us with a problem for the material that has no active link...

Is there any such material? Can't see any. Happy to just strip all the quotation marks instead

**Comment by weefuzzy** [comment]
Ok, I've just removed them for now. They can always come back if we want

**Comment by tremblap** [comment]
go for it and we'll cross the bridge at the river

**Pull request closed without merging**
